# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: Generate Snake

on:
  schedule:
    # run automatically every 12 hours
    - cron: "0 */1 * * *"

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

  # run on every push on the master branch
  push:
    branches:
      - master

# The sequence of runs in this workflow:
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Generates the snake
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
